org: abnerpersio
service: live055

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64

package:
  individually: true

esbuild:
  bundle: true
  minify: true
  sourcemap: false
  exclude:
    - '@aws-sdk/*'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
