org: abnerpersio
service: live055

provider:
  name: aws
  runtime: nodejs22.x
  architecture: arm64

package:
  individually: true

esbuild:
  bundle: true
  minify: true
  sourcemap: false
  exclude:
    - '@aws-sdk/*'

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - httpApi:
          path: /
          method: GET
  upload:
    handler: src/functions/upload.handler
    events:
      - httpApi:
          path: /
          method: POST
  users:
    handler: src/functions/users/index.handler
    events:
      - httpApi:
          path: /users
          method: ANY
      - httpApi:
          path: /users/{userId+}
          method: ANY
